name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # 如果在你的项目中已经有go.mod文件，你可以移除下面的这个步骤
    - name: Initialize Go module
      run: go mod init github.com/STFQ/network-metrics

    - name: Download dependencies
      run: go mod download
      # 这个步骤会下载所有依赖到本地缓存

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o network-metrics-server main.go

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: network-metrics-${{ github.run_id }}
        path: ./network-metrics-server
